### ISSUE TITLE
Install on Windows 10 and Matlab 2018a

### ISSUE THREAD

**Issue by Sirplentifus** [skycaptain/openexr-matlab#4]
Hello,

Is it possible to install this in Matlab 2018a on a Windows 10 machine? Your instructions require using homebrew, but that is not possible in Windows10. What should I do instead?

Thank you,
Sirplentifus

**Comment by skycaptain** [comment]
I'm sorry, I do not support this software anymore. Please, have a look at the original project on bitbucket: https://bitbucket.org/edgarv/hdritools/downloads/. They've got compiled binaries in their download section now.
